name: travel_operations_analytics
version: '1.0.0'
config-version: 2

profile: travel_operations_analytics

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  travel_operations_analytics:
    staging:
      +materialized: view
      +schema: STAGING
    intermediate:
      +materialized: view
      +schema: INTERMEDIATE
    marts:
      +materialized: table
      +schema: ANALYTICS
