select
    trip_id,
    employee_id,
    department,
    country_code,
    booking_session_id,
    booking_timestamp,
    cast(booking_timestamp as date) as booking_date,
    departure_date,
    return_date,
    datediff('day', cast(booking_timestamp as date), departure_date) as advance_purchase_days,
    origin_city_code,
    destination_city_code,
    airline_name,
    hotel_chain,
    booked_cost_usd,
    trip_status,
    iff(trip_status = 'completed', true, false) as is_completed,
    iff(trip_status = 'cancelled', true, false) as is_cancelled,
    policy_rule,
    policy_result,
    iff(policy_result = 'pass', true, false) as is_in_policy,
    is_material_violation,
    exception_reason,
    expense_count,
    expense_amount_usd,
    expenses_with_receipt_count,
    approved_expense_count,
    support_case_count,
    iff(support_case_count > 0, true, false) as has_support_case,
    average_resolution_hours
from {{ ref('int_trip_enriched') }}
