-- Lesson 9: dedicated read-only Snowflake identity for ThoughtSpot.
-- Run as ACCOUNTADMIN in this learning account.
-- Replace the password placeholder before running; never commit or share it.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TRAVEL_ANALYTICS_BI
  COMMENT = 'Read-only analytics role for ThoughtSpot in the Travel Operations Analytics Lab';

GRANT USAGE ON WAREHOUSE TRAVEL_ANALYTICS_XS TO ROLE TRAVEL_ANALYTICS_BI;
GRANT USAGE ON DATABASE TRAVEL_ANALYTICS TO ROLE TRAVEL_ANALYTICS_BI;
GRANT USAGE ON SCHEMA TRAVEL_ANALYTICS.ANALYTICS TO ROLE TRAVEL_ANALYTICS_BI;
GRANT SELECT ON ALL TABLES IN SCHEMA TRAVEL_ANALYTICS.ANALYTICS TO ROLE TRAVEL_ANALYTICS_BI;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRAVEL_ANALYTICS.ANALYTICS TO ROLE TRAVEL_ANALYTICS_BI;

CREATE USER IF NOT EXISTS TRAVEL_ANALYTICS_THOUGHTSPOT
  LOGIN_NAME = 'TRAVEL_ANALYTICS_THOUGHTSPOT'
  DISPLAY_NAME = 'Travel Analytics ThoughtSpot reader'
  PASSWORD = '<REPLACE_WITH_A_NEW_LONG_UNIQUE_PASSWORD>'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_ROLE = TRAVEL_ANALYTICS_BI
  DEFAULT_WAREHOUSE = TRAVEL_ANALYTICS_XS
  DEFAULT_NAMESPACE = 'TRAVEL_ANALYTICS.ANALYTICS'
  COMMENT = 'Read-only local ThoughtSpot identity for the Travel Operations Analytics Lab';

GRANT ROLE TRAVEL_ANALYTICS_BI TO USER TRAVEL_ANALYTICS_THOUGHTSPOT;

-- Verify role grants and user creation. These do not expose the password.
SHOW GRANTS TO ROLE TRAVEL_ANALYTICS_BI;
SHOW USERS LIKE 'TRAVEL_ANALYTICS_THOUGHTSPOT';
