-- Lesson 10: least-privilege Snowflake identity for the local MCP service.
-- Run as ACCOUNTADMIN in this learning account.
-- Replace the password placeholder before running; never commit or share it.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TRAVEL_ANALYTICS_MCP_READER
  COMMENT = 'Read-only, mart-only role for the Travel Operations Analytics MCP service';

GRANT USAGE ON WAREHOUSE TRAVEL_ANALYTICS_XS TO ROLE TRAVEL_ANALYTICS_MCP_READER;
GRANT USAGE ON DATABASE TRAVEL_ANALYTICS TO ROLE TRAVEL_ANALYTICS_MCP_READER;
GRANT USAGE ON SCHEMA TRAVEL_ANALYTICS.ANALYTICS TO ROLE TRAVEL_ANALYTICS_MCP_READER;

-- Deliberately grant only the two daily KPI marts used by the tools below.
-- There is no access to RAW, STAGING, INTERMEDIATE, employee-level facts,
-- and no arbitrary-SQL tool in the MCP server.
GRANT SELECT ON TABLE TRAVEL_ANALYTICS.ANALYTICS.MART_PRODUCT_DAILY
  TO ROLE TRAVEL_ANALYTICS_MCP_READER;
GRANT SELECT ON TABLE TRAVEL_ANALYTICS.ANALYTICS.MART_OPERATIONS_DAILY
  TO ROLE TRAVEL_ANALYTICS_MCP_READER;

CREATE USER IF NOT EXISTS TRAVEL_ANALYTICS_MCP_SERVICE
  LOGIN_NAME = 'TRAVEL_ANALYTICS_MCP_SERVICE'
  DISPLAY_NAME = 'Travel Analytics MCP service reader'
  PASSWORD = '<REPLACE_WITH_A_NEW_LONG_UNIQUE_PASSWORD>'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_ROLE = TRAVEL_ANALYTICS_MCP_READER
  DEFAULT_WAREHOUSE = TRAVEL_ANALYTICS_XS
  DEFAULT_NAMESPACE = 'TRAVEL_ANALYTICS.ANALYTICS'
  COMMENT = 'Local development identity; read-only access to daily KPI marts only';

GRANT ROLE TRAVEL_ANALYTICS_MCP_READER TO USER TRAVEL_ANALYTICS_MCP_SERVICE;

-- Verification only: neither statement exposes the password.
SHOW GRANTS TO ROLE TRAVEL_ANALYTICS_MCP_READER;
SHOW USERS LIKE 'TRAVEL_ANALYTICS_MCP_SERVICE';
